name: tweekey
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mfm: ^1.0.7+1
  flutter_riverpod: ^2.4.9
  auto_route: ^7.8.4
  freezed: ^2.4.6
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  misskey_dart:
    git: https://github.com/shiosyakeyakini-info/misskey_dart.git
  mfm_parser: ^1.0.5
  collection: ^1.18.0
  font_awesome_flutter: ^10.6.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png