name: tweekey
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mfm: ^1.0.7+1
  hooks_riverpod: ^3.0.0-dev.15
  auto_route: ^10.0.1
  freezed: ^3.0.0
  riverpod_annotation: ^3.0.0-dev.15
  freezed_annotation: ^3.0.0
  misskey_dart:
    git: 
      url: https://github.com/shiosyakeyakini-info/misskey_dart.git
      ref: feature/migrate_freezed3
  mfm_parser: ^1.0.5
  collection: ^1.18.0
  font_awesome_flutter: ^10.6.0
  flutter_secure_storage: ^10.0.0-beta.4
  intl: ^0.20.2
  url_launcher: ^6.2.4
  flutter_hooks:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  riverpod_generator: ^3.0.0-dev.15
  json_serializable: ^6.9.5
  frontend_server_client: ^4.0.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png